name: Terraform Deploy

on:
  push:
    branches:
      - development
      - main

jobs:
  terraform-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1 

      - name: Init Terraform
        working-directory: infrastructure
        run: terraform init

      - name: Configure environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            ENV_FILE="./environments/production/terraform.tfvars"
          elif [[ ${{ github.ref }} == 'refs/heads/development' ]]; then
            ENV_FILE="./environments/dev/terraform.tfvars"
          fi
          echo "ENV_FILE=${ENV_FILE}" >> $GITHUB_ENV

      - name: Apply Terraform changes
        working-directory: infrastructure
        run: terraform apply -var-file=${{ env.ENV_FILE }} -auto-approve
